### ISSUE TITLE
触摸长按事件的支持时间问题

### ISSUE THREAD

**Issue by wanghang7894** [ShawnZhang2015/uikiller#1]
首先非常感谢您提供这么好用的插件。
在长按事件时，您的教程里说：
//控制长按触摸触发时间0.5秒，不要这句代码，默认1秒触发
 this._buttonOk.touchLongTime = 0.5; 
实际上看源码这个值的单位是毫秒：
        node.on(cc.Node.EventType.TOUCH_START, (event) => {
            node._touchLongTimer = setTimeout(() => {
                //准备触发touchLong事件
                node.interactable = !!touchLong.call(target, node, event);
                node._touchLongTimer = 0;
            }, node.touchLongTime || 1000);

**Comment by ShawnZhang2015** [comment]
感谢你的指正，代码中确实是以毫秒为单位，《奎特尔星球—雷神之锤》文档中注释有误。
我在Readme中更新了正式的使用手册《uikiller使用手册》。
