### ISSUE TITLE
關閉Button遇到的問題

### ISSUE THREAD

**Issue by sandfresh** [ShawnZhang2015/uikiller#3]
![擷取2](https://user-images.githubusercontent.com/9217944/67840794-9a2b2980-fb31-11e9-8cb7-c8b57f57051f.PNG)
我今天在使用上遇到一個很奇怪的問題
如圖_btnShowPanel是節點樹上最後一個active true的節點
如果我把_btnShowPanel上面的button設為interactable = false
或者是enable = false ,畫面上所有按鈕都無法點擊
但是我把_btnShowPanel往上移一個節點就不會發生這個問題

**Comment by sandfresh** [comment]
大概知道原因了
因為最後一個節點touch是最上層
所以在touch事件會優先
然後沒判斷範圍 
所以在button interactable false
就return了
導致所有按鈕都按不到

**Comment by ShawnZhang2015** [comment]
不好意思，没有即时回复你，找到问题就好，你可以加我微信或QQ，有问题方便沟通，感谢你的支持
QQ：6346289
微信：z6346289
